name: walkit
description: "A lifestyle dapp to pays you to walk"
publish_to: 'none'
version: 0.0.1
# version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # change_app_package_name: ^1.5.0
  # rename_app: ^1.6.2 # dart run rename_app:main all="My App Name"
  # flutter_launcher_icons: ^0.14.3  # dart run flutter_launcher_icons
  # flutter_launcher_icons: ^0.13.1
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  google_sign_in: ^6.2.2
  http: ^1.3.0
  riverpod: ^2.6.1
  shared_preferences: ^2.3.3
  action_slider: ^0.7.0
  lottie: ^1.4.3
  line_icons: ^2.0.3
  flutter_animated_icons: ^1.0.1
  permission_handler: ^11.3.1
  geolocator: ^11.0.0
  appcheck: ^1.0.6
  url_launcher: ^6.2.6
  health: ^12.0.1
  random_avatar: ^0.0.8
  intl: ^0.18.1
  share_plus: ^9.0.0
  confetti: ^0.7.0
  percent_indicator: ^4.2.3
  flutter_local_notifications: ^18.0.1
  # workmanager: ^0.5.2
  # flutter_foreground_task: ^8.17.0
  # flutter_background_service
  flutter_foreground_task: ^8.17.0
  firebase_core: ^3.4.0
  json_annotation: 4.9.0
  firebase_auth: ^5.2.0
  flutter_dotenv: ^5.2.1
    


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.9


flutter:
  uses-material-design: true
  assets:
    - .env
    - shorebird.yaml
    - assets/
    - assets/3d/

    
  fonts:
    - family:  WalkItIcons
      fonts:
        - asset: assets/fonts/WalkItIcons.ttf
        # - asset: assets/walk_it_iconography/walk_it_icons.dart
        # - asset: assets/walk_it_iconography/WalkItIcons.ttf
    
    # evil empire
    - family: EvilEmpire
      fonts:
        - asset: assets/fonts/Evil_Empire/EvilEmpire.otf

    #  montserrat
    - family: MontserratAlternates
      fonts:
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-ThinItalic.ttf
          weight: 100
          style: italic

    
